### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by ugogo** [MoOx/atom-smart-tab-name#1]
Maybe because of
- icons?
- text is too long?

<img width="1392" alt="capture d ecran 2015-07-24 a 09 58 02" src="https://cloud.githubusercontent.com/assets/5040476/8870255/cf306446-31ec-11e5-8988-b758486cc951.png">

**Comment by MoOx** [comment]
From my memory, some icons plugins and this plugin use the same element/technique to be introduced. I will see if I can fix that or if it's an issue with the other plugins.

**Comment by mezcala** [comment]
I have the same problem with the "file-icons" plugin. A simple `display: inline-block` on `.smart-tab-name` seems to fix it.

**Comment by MoOx** [comment]
You mean "display: inline-block" ?

**Comment by mezcala** [comment]
Yes sorry, it's friday…

**Comment by bronson** [comment]
I had the same problem, recorded a screen cap before I realized this bug was already open.

![bug3](https://cloud.githubusercontent.com/assets/1776/8966425/2ee2cef4-35e6-11e5-8aa5-9ba489c1e722.gif)

Nice one @whoisthecoon, putting that in `~/.atom/styles.less` does fix it.

```
.smart-tab-name {
  display: inline-block
}
```

**Comment by MoOx** [comment]
Fixed in 1.0.2. Thanks for the workaround.
