### ISSUE TITLE
add an option to remove the fading effect

### ISSUE THREAD

**Issue by Nyalab** [MoOx/atom-smart-tab-name#12]
nice package!

it could be nice to have the ability to remove this effect, and maybe adding "..." to the begining of the filename

**Comment by MoOx** [comment]
This plugin is a pile of crappy trick, so I end up with the fade because the ellipsis was really hard to achieve :/

**Comment by Nyalab** [comment]
oh ok, so nervemind, i will take a look some day if i have the time but don't worry about it
