### ISSUE TITLE
Tab should prefer filename visibility

### ISSUE THREAD

**Issue by aaronjensen** [MoOx/atom-smart-tab-name#2]
Right now, if the tab isn't wide enough for the file + directory, the filename is cut off. Ideally, it'd be right justified and the directory would be cut off instead.

![atom 2015-07-25 00-15-21](https://cloud.githubusercontent.com/assets/8588/8888452/4edcbf6c-3262-11e5-930f-44c545e26b08.png)

**Comment by Xaviju** [comment]
+1

Thanks for the plugin!

**Comment by bronson** [comment]
Yep, I just came here to report this too.  2 for 2!

When I get a few tabs open, I can't tell what file I'm looking at anymore.  Makes it hard to use smart-tab-name.

![bug3](https://cloud.githubusercontent.com/assets/1776/8972892/6228b972-3613-11e5-9409-9e884f61c7a9.gif)

**Comment by MoOx** [comment]
Should be better in 1.0.2.
Tell me what you think of the way I handled this issue.
