### ISSUE TITLE
Display bug when name is short

### ISSUE THREAD

**Issue by ugogo** [MoOx/atom-smart-tab-name#5]
<img width="401" alt="capture d ecran 2015-08-14 a 15 22 25" src="https://cloud.githubusercontent.com/assets/5040476/9274744/7debf20a-4298-11e5-8276-35f1321c2698.png">

**Comment by MoOx** [comment]
it's probably a side effect of your theme. What do you use for the icons ?

**Comment by ugogo** [comment]
UI Theme: Seti
Syntax Theme: Material (atom-material-ui)

**Comment by CosticaPuntaru** [comment]
the icon most likely uses mask, you can overwrite it in your style

**Comment by MoOx** [comment]
Is this still relevant?

**Comment by ugogo** [comment]
Idk, I'm not using this plugin anymore.
