### ISSUE TITLE
Tab name falls back to just the filename after dragging tab

### ISSUE THREAD

**Issue by ghost** [MoOx/atom-smart-tab-name#7]
Filenames render fine normally (parent folder is displayed, ellipsis etc.). But when I drag a tab to another place in the tab bar, the name returns to just the filename (and it stays that way).

Atom: 1.0.11
Smart-tab-name: 1.0.3
Theme: One Dark
Syntax theme: Base16 Tomorrow Dark

**Comment by Zequez** [comment]
There I made a pull request to fix this, it seems moving tabs re-rendered the panel, so I just added a subscription to that event to re-process them. https://github.com/MoOx/atom-smart-tab-name/pull/8

**Comment by ghost** [comment]
Thanks!
